server:
  port: 14000
spring:
  profiles:
    include: sharding
  datasource:
    url: jdbc:mysql://192.168.6.99:3306/gmall_order?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    type: com.zaxxer.hikari.util.DriverDataSource