server:
  port: 16000
spring:
  datasource:
    url: jdbc:mysql://192.168.6.99:3306/gmall_activity?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource