server:
  port: 80
#配置跨域
spring:
  zipkin:
    base-url: http://192.168.6.99:9411/
    sender:
      type: web
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': #只要有人处理请求了，这个跨域就能生效
            allowedOrigins: "*" #允许所有地址来源跨域
            allowedMethods: "*" #允许所有请求方式跨域
            allowedHeaders: "*"
            allowCredentials: true #允许带一些安全标致跨域 比如：Cookie

     #      所有网关路由规则
      routes:
        - id: product_route # 以 /admin/product 开头的所有请求都lb(loadbalancer)转给service-product
          uri: lb://service-product
          predicates: #断言
            - Path=/admin/product/**
        - id: activity_route # 以 /admin/activity 开头的所有请求都lb(loadbalancer)转给service-activity
          uri: lb://service-activity
          predicates:
            - Path=/admin/activity/**

        - id: user_route
          uri: lb://service-user
          predicates:
              - Path=/api/user/**
        - id: item_route # 以 /admin/activity 开头的所有请求都lb(loadbalancer)转给service-activity
          uri: lb://service-item
          predicates:
            - Path=/api/inner/rpc/item/**
        - id: web_all_route  # 以 **.gmall.com开头的所有请求都lb(loadbalancer)转给web-all
          uri: lb://web-all
          predicates:
            - Host=**.gmall.com