server:
  port: 9000
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  zipkin:
    base-url: http://192.168.6.99:9411/
    sender:
      type: web