server:
  port: 8000
spring:
  profiles:
    include: sharding
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.6.99:3306/gmall_product?useSSL=false&characterEncoding=utf-8

app:
  minio:
    endpoint: http://192.168.6.99:9000
    ak: admin
    sk: admin123456
    bucket-name: gmall
  thread-pool:
    core: 4
    max: 8
