spring:
  zipkin:
    base-url: http://192.168.6.99:9411/
    sender:
      type: web
  redis:
    host: 192.168.6.99
    password: gby19980810
feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 5000